# safelist
branches:
  only:
  - master
  - develop


language: node_js
sudo: false
node_js:
  - "stable"
install:
  — npm install phantomjs -g
  — npm install -g mocha-phantomjs
  — npm install -g gulp
  — npm install -g bower
  — npm install
  — bower install
script:
  - npm test