# safelist
branches:
  only:
  - master
  - develop


language: node_js
sudo: false
node_js:
  - "stable"
install:
  - npm install -g mocha-phantomjs
  - npm install phantomjs -g
  - npm install -g gulp
  - npminstall -g bower
  - npm install
script:
  - npm test